# Generated by Django 5.2.7 on 2025-10-30 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='PendingEnrollment',
            fields=[
            ],
            options={
                'verbose_name': 'Enrollment Request (Pending)',
                'verbose_name_plural': 'Enrollment Requests (Pending)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('enrollments.enrollment',),
        ),
        migrations.CreateModel(
            name='VerifiedEnrollment',
            fields=[
            ],
            options={
                'verbose_name': 'Verified Enrollment',
                'verbose_name_plural': 'Verified Enrollments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('enrollments.enrollment',),
        ),
    ]
