# Generated by Django 5.2.7 on 2025-10-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='template_image',
        ),
        migrations.AddField(
            model_name='certificate',
            name='template_file',
            field=models.FileField(blank=True, upload_to='certificates/templates/'),
        ),
    ]
