# Generated by Django 5.2.7 on 2025-10-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='mentors/photos/'),
        ),
    ]
