# Generated by Django 5.2.7 on 2025-10-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_mentorprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='current_company',
            field=models.CharField(blank=True, help_text='Current company or organization name', max_length=255),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='experience',
            field=models.PositiveIntegerField(default=0, help_text='Years of professional experience'),
        ),
    ]
